synonyms = {
    'Software Developer': ['software developer', 'software engineer', 'application developer'],
    'Systems Analyst': ['systems analyst', 'business systems analyst', 'IT systems analyst'],
    'Network Administrator': ['network administrator', 'network engineer', 'network specialist'],
    'IT Support Specialist': ['IT support specialist', 'technical support specialist', 'help desk technician'],
    'Database Administrator': ['database administrator', 'DBA', 'database manager'],
    'Systems Engineer': ['systems engineer', 'systems architect', 'infrastructure engineer'],
    'IT Consultant': ['IT consultant', 'technology consultant', 'IT advisor'],
    'Web Developer': ['web developer', 'web programmer', 'front-end developer'],
    'Cybersecurity Analyst': ['cybersecurity analyst', 'information security analyst', 'security analyst'],
    'Technical Support Engineer': ['technical support engineer', 'support engineer', 'IT support engineer'],
    'DevOps Engineer': ['DevOps engineer', 'site reliability engineer', 'build engineer'],
    'IT Project Manager': ['IT project manager', 'technology project manager', 'IT program manager'],
    'Cloud Architect': ['cloud architect', 'cloud solutions architect', 'cloud engineer'],
    'Application Developer': ['application developer', 'app developer', 'mobile developer'],
    'Information Systems Manager': ['information systems manager', 'IT manager', 'IS manager'],
    'Data Scientist': ['data scientist', 'data analyst', 'data engineer'],
    'UX/UI Designer': ['UX/UI designer', 'user experience designer', 'user interface designer'],
    'IT Director': ['IT director', 'information technology director', 'IT head'],
    'Computer Programmer': ['computer programmer', 'programmer', 'coder'],
    'IT Auditor': ['IT auditor', 'information systems auditor', 'IT compliance auditor'],
    'Machine Learning Engineer': ['machine learning engineer', 'ML engineer', 'AI engineer'],
    'Network Engineer': ['network engineer', 'network systems engineer', 'network architect'],
    'Business Analyst': ['business analyst', 'IT business analyst', 'systems business analyst'],
    'Software Architect': ['software architect', 'application architect', 'solutions architect'],
    'Technical Writer': ['technical writer', 'documentation specialist', 'technical communicator'],
    'IT Trainer': ['IT trainer', 'technology trainer', 'IT instructor'],
    'IT Coordinator': ['IT coordinator', 'technology coordinator', 'IT administrator'],
    'Systems Administrator': ['systems administrator', 'sysadmin', 'IT systems administrator'],
    'Cloud Engineer': ['cloud engineer', 'cloud systems engineer', 'cloud solutions engineer'],
    'Penetration Tester': ['penetration tester', 'pentester', 'ethical hacker'],
    'BI Developer': ['BI developer', 'business intelligence developer', 'BI analyst'],
    'Scrum Master': ['scrum master', 'agile coach', 'scrum lead'],
    'IT Specialist': ['IT specialist', 'information technology specialist', 'IT technician'],
    'Network Security Engineer': ['network security engineer', 'network security analyst', 'network security administrator'],
    'Information Security Manager': ['information security manager', 'IT security manager', 'cybersecurity manager'],
    'E-commerce Specialist': ['e-commerce specialist', 'e-commerce manager', 'online business specialist'],
    'System Architect': ['system architect', 'systems architect', 'IT architect'],
    'Data Engineer': ['data engineer', 'big data engineer', 'data infrastructure engineer'],
    'Game Developer': ['game developer', 'game programmer', 'video game developer'],
    'CRM Developer': ['CRM developer', 'customer relationship management developer', 'CRM specialist'],
    'IT Operations Manager': ['IT operations manager', 'IT operations lead', 'IT operations supervisor'],
    'Full Stack Developer': ['full stack developer', 'full stack engineer', 'full stack programmer'],
    'Mobile Developer': ['mobile developer', 'mobile app developer', 'mobile application developer'],
    'QA Engineer': ['QA engineer', 'quality assurance engineer', 'software tester'],
    'Embedded Systems Engineer': ['embedded systems engineer', 'embedded software engineer', 'embedded developer'],
    'Product Manager': ['product manager', 'IT product manager', 'tech product manager'],
    'Big Data Engineer': ['big data engineer', 'big data developer', 'big data specialist'],
    'ERP Consultant': ['ERP consultant', 'enterprise resource planning consultant', 'ERP specialist'],
    'Webmaster': ['webmaster', 'web administrator', 'site administrator'],
    'Storage Administrator': ['storage administrator', 'storage engineer', 'SAN administrator'],
    'Help Desk Analyst': ['help desk analyst', 'help desk technician', 'IT support analyst'],
    'Systems Integrator': ['systems integrator', 'IT integrator', 'systems integration specialist'],
    'Video Game Designer': ['video game designer', 'game designer', 'interactive media designer'],
    'Blockchain Developer': ['blockchain developer', 'blockchain engineer', 'distributed ledger developer'],
    'IT Asset Manager': ['IT asset manager', 'IT asset coordinator', 'technology asset manager'],
    'VoIP Engineer': ['VoIP engineer', 'voice engineer', 'voice over IP engineer'],
    'Telecom Engineer': ['telecom engineer', 'telecommunications engineer', 'telecom systems engineer'],
    'Release Manager': ['release manager', 'release engineer', 'deployment manager'],
    'GIS Analyst': ['GIS analyst', 'geographic information systems analyst', 'GIS specialist'],
    'Virtualization Engineer': ['virtualization engineer', 'virtualization specialist', 'virtualization administrator'],
    'Site Reliability Engineer': ['site reliability engineer', 'SRE', 'reliability engineer'],
    'SEO Specialist': ['SEO specialist', 'search engine optimization specialist', 'SEO analyst'],
    'IT Recruiter': ['IT recruiter', 'technology recruiter', 'technical recruiter'],
    'Technology Evangelist': ['technology evangelist', 'tech evangelist', 'developer advocate'],
    'BI Analyst': ['BI analyst', 'business intelligence analyst', 'BI specialist'],
    'Cloud Security Engineer': ['cloud security engineer', 'cloud security specialist', 'cloud security architect'],
    'Application Support Analyst': ['application support analyst', 'app support analyst', 'application support specialist'],
    'E-learning Specialist': ['e-learning specialist', 'e-learning developer', 'online learning specialist'],
    'Technical Account Manager': ['technical account manager', 'TAM', 'client technical manager'],
    'Information Architect': ['information architect', 'IA', 'data architect'],
    'Network Analyst': ['network analyst', 'network systems analyst', 'network infrastructure analyst'],
    'Robotics Engineer': ['robotics engineer', 'robotics developer', 'robotic systems engineer'],
    'IT Compliance Manager': ['IT compliance manager', 'IT compliance officer', 'technology compliance manager'],
    'IoT Developer': ['IoT developer', 'Internet of Things developer', 'IoT engineer'],
    'IT Vendor Manager': ['IT vendor manager', 'technology vendor manager', 'IT supplier manager'],
    'IT Service Manager': ['IT service manager', 'ITSM manager', 'service delivery manager'],
    'Digital Forensics Analyst': ['digital forensics analyst', 'cyber forensics analyst', 'computer forensics analyst'],
    'UX Researcher': ['UX researcher', 'user experience researcher', 'UX analyst'],
    'Solutions Architect': ['solutions architect', 'solution architect', 'technology solutions architect'],
    'Security Consultant': ['security consultant', 'IT security consultant', 'cybersecurity consultant'],
    'Chief Information Officer': ['chief information officer', 'CIO', 'IT director'],
    'Chief Technology Officer': ['chief technology officer', 'CTO', 'technology director'],
    'ERP Developer': ['ERP developer', 'enterprise resource planning developer', 'ERP programmer'],
    'IT Risk Manager': ['IT risk manager', 'technology risk manager', 'IT risk analyst'],
    'Cloud Consultant': ['cloud consultant', 'cloud advisor', 'cloud solutions consultant'],
    'DevSecOps Engineer': ['DevSecOps engineer', 'security-focused DevOps engineer', 'DevOps security engineer'],
    'IT Facilities Manager': ['IT facilities manager', 'technology facilities manager', 'IT infrastructure manager'],
    'Cybersecurity Engineer': ['cybersecurity engineer', 'information security engineer', 'security engineer'],
    'Technical Product Manager': ['technical product manager', 'tech product manager', 'IT product manager'],
    'IT Infrastructure Manager': ['IT infrastructure manager', 'infrastructure manager', 'IT infrastructure lead'],
    'IT Governance Manager': ['IT governance manager', 'technology governance manager', 'IT governance lead'],
    'Mobile Security Engineer': ['mobile security engineer', 'mobile security specialist', 'mobile cybersecurity engineer'],
    'IT Operations Analyst': ['IT operations analyst', 'IT operations specialist', 'IT ops analyst'],
    'Software Tester': ['software tester', 'QA tester', 'quality assurance tester'],
    'Tech Support Specialist': ['tech support specialist', 'technical support specialist', 'IT support specialist']
}

uniqueTitles = [
    'Technical Consultant',
    'Web Application Developer',
    'Data Integration Developer',
    'Web Development Product Manager',
    'Digital Architect',
    'Developer and Engineering Leader',
    'Digital Technology Project Manager',
    'Technology Executive',
    'Technical Services Manager',
    'Digital Marketing',
    'Digital Media Professional',
    'Software Support Analyst',
    'system administrator',
    'Security Operations Analyst',
    'Analyst and Technical Communicator',
    'Cloud Solution Architect ',
    'Software Business Analyst',
    'Data Center Services',
    'Data Integration Developer II',
    'Technical Project',
    'Technology Consulting Manager',
    'Technical Business Services Manager',
    'Software Integrity Engineer',
    'Technical Trainer for instructor',
    'Software Engineer Sr Staff',
    'Software Technical Writer',
    'AI software Engineer',
    'Technical Services Developer',
    'System Developer',
    'Data Visualization and Analytics',
    'System Administrator ',
    'Database Architect',
    'Data Quality Manager',
    'Software Backend Engineer',
    'Software Quality Manager',
    'Software Integration Intern',
    'Software Team Lead',
    'Software Engineer Technical Manager',
    'Network Systems Administrator',
    'Network Team Lead',
    'System and Network Administrator',
    'NETWORK ADMINISTRATOR',
    'Data Network Manager',
    'Network Engineer',
    'Digital Coach',
    'Network Operations Engineer',
    'Technical Product Manager with ',
    'Software Solutions Leader',
    'Data Warehouse Architect',
    'Technical Support Team Leader',
    'Data Scientist',
    'Technical Service and V',
    'cloud solution architect',
    'Software Programmer',
    'Data Warehouse Engineer',
    'SOFTWARE ENGINEERING ADVISOR',
    'Data Engineer',
    'Technical Support Engineer',
    'software engineer',
    'Developer and Designer',
    'System Analyst III',
    'Software QA Test Analyst',
    'Technical Product Manager',
    'Technical Product Specialist',
    'Technical Service Manager',
    'Database Engineer',
    'Programmer Analyst I',
    'Cloud Solutions Engineer',
    'Technology Recruiter',
    'Software engineer II',
    'Data scientist with ',
    'Digital marketing and sales',
    'Security manager',
    'Software Engineering Intern',
    'Data Analytics Consultant',
    'Web and Application Designer',
    'Web Producer',
    'Web Developer',
    'Software Verification Engineer I',
    'Network Operations Center Administrator',
    'Digital Marketing Specialist',
    'Software Analyst',
    'Technical Content DevOps Specialist',
    'Network Engineer with ',
    'System designer',
    'Software Sr',
    'Web Master',
    'Software Engineer Staff',
    'Digital Marketing Strategist',
    'Cloud Computing',
    'Web And Software Developer',
    'Data Management Consultant',
    'Data Management Technical Lead',
    'network administrator',
    'Software Developer In Test',
    'Data Center Solutions Architect',
    'Software Engineering Senior Analyst',
    'Data Analytics Student',
    'Technical Delivery Team Manager',
    'Software Engineer Contractor',
    'System Quality Assurance Analyst',
    'Web Design and Development',
    'Support System Administrator',
    'Security Researcher',
    'Engineer V',
    'Network Security Support Engineer',
    'Developer Support Engineer',
    'SOFTWARE QA TESTER',
    'Cybersecurity Professional',
    'DevOps Intern',
    'Software Engineer Student',
    'Software Engineering Major',
    'Devops Automation Engineer',
    'Technology Engineer',
    'Data Center Software Engineering',
    'Technology Investment Banking',
    'Data Processing Specialist',
    'Technical Sourcing Recruiter',
    'data analyst',
    'Technology leader',
    'Software Project Lead',
    'Software Developer Technical Lead',
    'Software Development Consultant',
    'Software Development Leader',
    'Software Technical Lead',
    'Engineer Associate',
    'Digital Manager',
    'Security Systems Engineer',
    'Network Engineering Consultant',
    'Database Advisor',
    'Software Developer I',
    'Technical Operations Supervisor',
    'CyberSecurity Administrator',
    'Network Infrastructure',
    'Software Engineer Graduate',
    'Technical Sales Leader',
    'Technology Supervisor',
    'Technical Implementation Specialist',
    'Software consultant',
    'DevOps Database Engineer',
    'Technical Project Coordinator',
    'Network and Systems Administrator',
    'Technical Recruiter',
    'AI Developer',
    'Software Engineer Consultant',
    'Cybersecurity Architect',
    'Database Manager',
    'Technical Analyst',
    'Cloud Solution Architect',
    'Technical Professional',
    'Network Analyst',
    'Software Engineering Student',
    'Digital Transformation Advisor',
    'Cloud Specialist Solutions Architect',
    'Network And System Administrator',
    'Software Lead Engineer',
    'Technology Product Manager',
    'Technology Management',
    'Technology Support',
    'Data Engineer Consultant',
    'Data Science Co',
    'Database developer',
    'Security Contractor',
    'Security Rep',
    'Analyst III',
    'Cloud Systems Administrator',
    'Digital Experience Project',
    'Cloud Team Lead',
    'Software Consultant',
    'Technical Support Manager',
    'Network Enablement Lead',
    'Database Engineering Manager',
    'Technology Specialist',
    'Data Management Coordinator',
    'Security Analyst and Researcher',
    'Technical Services Specialist',
    'Technology Systems Analyst I',
    'Cybersecurity Master',
    'Security Systems Administrator',
    'Data Analytics Lead',
    'Software Dev Engineer',
    'Technical Project Manager',
    'Software Engineering Executive',
    'Engineer and Manager',
    'Technical Solutions Consultant',
    'Network and Infrastructure Manager',
    'Software Product Manager',
    'Digital Operations',
    'Infrastructure Engineer III',
    'CyberSecurity Consultant',
    'Software Engineer Data II',
    'Software Engineer MTS',
    'Data Engineer Analyst',
    'Software Quality Assurance engineer',
    'Software developer',
    'Network Operations',
    'Software Engineering Product Manager',
    'Support Team Lead',
    'Technical Lead Manager',
    'Technical Support Supervisor',
    'Software Engineer Technical Lead',
    'System Engineer I',
    'Programmer Analyst',
    'Data Analyst III',
    'Data Enthusiast',
    'Software Engineer',
    'Data Enablement Lead',
    'Software Sales Executive',
    'Support Center Supervisor',
    'Programmer and Consultant',
    'DevOps Consultant',
    'Security Supervisor',
    'System Design Engineer',
    'Web designer Expert',
    'Technical Project Lead',
    'Technical Engineer II',
    'Support Specialist',
    'Digital Design Project Manager',
    'Technical Implementation Associate',
    'Technical Support Professional',
    'Software professional',
    'Network Operations Center Manager',
    'Security Professional',
    'Digital IT Leader',
    'Technical Security Project Manager',
    'Digital Producer',
    'System Specialist',
    'Software Engineering',
    'Web Manager',
    'Infrastructure Software Engineer',
    'Software engineer and technology',
    'Software Development Engineer II',
    'Security Specialist',
    'Technical Network Architect',
    'Technical Account Manager',
    'Data Entry',
    'Data Developer',
    'Software Senior Principal Engineer',
    'Cloud Solutions Architect',
    'Technical Marketing Manager',
    'Software Project Manager',
    'Software Developer Intern',
    'Software Test Analyst',
    'Network Developer Engineer',
    'Software Verification',
    'DEVOPS ENGINEER',
    'Network Architect',
    'Infrastructure Administrator',
    'Database Programmer',
    'Digital Strategy',
    'Software Engineer and Co',
    'System Supervisor',
    'Software Application Developer',
    'Software Quality Assurance Lead',
    'Network Administrator III',
    'Cloud Native Enablement',
    'Network Analyst II',
    'Data Analytics Engineer',
    'Security Director',
    'Software Engineer ',
    'Software Integration Engineer',
    'System Specialist II',
    'System programmer',
    'Technical Sales Director',
    'Technology Risk Consultant',
    'Network Operations Manager',
    'Cloud Technical Account Manager',
    'Programmer Systems Analyst',
    'Software Development Engineer',
    'Technical Manager',
    'Technical Lead Software Engineer',
    'Software Analyst Developer',
    'Digital Marketing Marketing Tech',
    'Data Science Professional',
    'Database Administrator Manager',
    'Database Progammer',
    'Software Executive',
    'Database Developer',
    'Web Design',
    'Cloud Administrator',
    'Network System Engineer',
    'Security Sales Engineer',
    'Technology Expert',
    'Software Principal Engineer',
    'Technical Recruiting',
    'Data Science Manager',
    'Data Management Specialist',
    'Cybersecurity Specialist III',
    'Data Analyst',
    'Support Technician I',
    'System Software Architect',
    'Technical Training Specialist',
    'Digital Project Manager',
    'System test',
    'Cloud Software Engineer',
    'software engineer and leader',
    'Technical Support Analyst',
    'Software Solutions Engineer',
    'Technology Coordinator',
    'Digital Transformation Leader',
    'Database developer III',
    'Technical Solutions Manager',
    'Data science',
    'Software System',
    'Technology Manager',
    'Security Focused IT Professional',
    'Technical support engineer',
    'Technology Technician',
    'Engineer II',
    'Network Development Engineer',
    'Software Dev',
    'Security Delivery Analyst',
    'Infrastructure System Administrator II',
    'Network engineer',
    'Data Analysis',
    'Analyst Developer',
    'Technology Management Executive',
    'technical Lead',
    'Security Officer ',
    'Network Administrator ',
    'Cybersecurity Program Manager',
    'Infrastructure Manager',
    'software developer',
    'Data Center Solutions',
    'Software engineer',
    'Network Development Senior Engineer',
    'Data Architect',
    'Technology Planning and Strategy',
    'Data Services Manager',
    'Database Administrator III',
    'Developer and Analyst',
    'Digital Sales Representative',
    'Security Delivery Manager',
    'Network Security Manager',
    'Software Engineer with ',
    'Software Quality Assurance',
    'Software Test Automation Engineer',
    'Network Director',
    'Network Administrator',
    'Technical Recruiting Team Lead',
    'Technical Services',
    'Software Development Project Manager',
    'System QA Lead',
    'Digital Experience',
    'software consultant',
    'Software development engineer',
    'Network Engineer III',
    'Technology focused business professional',
    'Technical Communicator',
    'Technical Expert and Strategist',
    'Software Engineer Data Scientist',
    'software engineer on test',
    'DevOps Engineering Supervisor',
    'Administrator ',
    'Technical Enterprise Architect',
    'Data Science and Analytics',
    'System Network Admin',
    'Cybersecurity Manager',
    'Technical Design Manager',
    'Web and Security Engineer',
    'network manager',
    'Technical Lead II',
    'Data Science Intern',
    'Database Systems Engineer',
    'Data Analytics Designer ',
    'Data Management Analyst III',
    'Data Specialist',
    'Cloud Engineer II',
    'Security Manager',
    'Technical content writer',
    'Technology Director',
    'Web Marketing Strategist',
    'Software Development Graduate',
    'Security Team Lead',
    'software dev',
    'Data Science and Engineering',
    'AI Research Scientist',
    'Security Operations Center Analyst',
    'Software Engineering Analyst',
    'Digital Marketing Sales',
    'Security Control Assessor',
    'System Support Specialist',
    'Technology Support Specialist',
    'Software Engineering Specialist',
    'Software Technical Manager',
    'Technical Support Rep',
    'Programmer analyst',
    'Data Strategy',
    'Developer Technology Engineer',
    'Technology manager',
    'Data Management Analyst',
    'Software Professional',
    'System Design and Architecture',
    'Software Dev Manager',
    'Technology and Product Leader',
    'Data Governance',
    'Network Coordinator',
    'Data Security Administrator',
    'Security consultant',
    'Technical Operations Specialist',
    'Technology Systems Analyst',
    'Software Engineering Supervisor',
    'Cybersecurity Engineering',
    'Data Administrator',
    'Technical Specialist',
    'Technology Consultant',
    'Data and Reporting Analyst',
    'DevOps Solutions Architect',
    'Cloud Engineering Intern',
    'Technical Solution Specialist',
    'Data Intern',
    'DevOps Engineer Lead',
    'Digital Engineer',
    'Web Programmer',
    'Web Product Manager',
    'Technical Artist',
    'Data Center Security Administrator',
    'Security Sales Leader',
    'DevOps Team Lead',
    'Data warehouse',
    'Cybersecurity Engineer',
    'Software Leader',
    'Data Operations Manager',
    'Digital Sales Manager',
    'Data Engineer III',
    'Technical Leader',
    'Web Administrator',
    'Cloud Enterprise Architect',
    'Software System Developer',
    'Digital Technology',
    'Data Management',
    'Software Manager',
    'Software Development Technical Lead',
    'Software Project Engineer',
    'System Architecture',
    'Software Developer',
    'Technology Strategy',
    'Technical Expert',
    'Digital Transformation Consultant',
    'security consultant',
    'Digital Engineering Leader',
    'DevOps Architect',
    'Technical Program Management',
    'Software Design Engineer',
    'Software Engineer Sr Stf',
    'Technical Business Systems Associate',
    'Data Network Administrator',
    'System Architect',
    'Data Advocate',
    'Technology Risk Manager',
    'Security Management',
    'Data Admin',
    'Software Development Engineering Manager',
    'Network Consultant',
    'Data Systems Network Administrator',
    'Technology Analyst',
    'Software Implementation Analyst',
    'DevOps Platform Automation Engineer',
    'Database Engineer II',
    'Technical Program Management Intern',
    'Web Developer and Co',
    'Technology Support Analyst',
    'Digital Sales Administrator',
    'Cloud Network Security Engineer',
    'Software Development',
    'Infrastructure Technology Support Specialist',
    'Technical Sales Consultant',
    'Technical Marketing Engineer',
    'Web Software Engineer',
    'Software Engineering Lead',
    'Software Validation Engineer',
    'Security Principal',
    'Digital Program Manager',
    'Software Developer Engineer',
    'Data Center',
    'Software Automation Specialist',
    'Digital Product Designer',
    'Network Design Engineer',
    'Data Management Manager',
    'Security Engineer ',
    'Software Specialist',
    'Software and Web Developer',
    'Technical Lead',
    'Data Engineering Director',
    'Technical Support Services',
    'Technical Product',
    'Data Integration Coordinator',
    'Security Manager III',
    'Technology Builder',
    'Software Engineer Intern',
    'Digital Marketing Specialist II',
    'WEB DEVELOPER',
    'Software Design Services Engineer',
    'Data Integrity Manager',
    'Cloud Specialist',
    'Technical Sales Manager',
    'Data Operations Intern',
    'Cybersecurity Specialist',
    'Data Analyst Senior',
    'Technology lead',
    'Technical Associate',
    'system analyst',
    'Software Engineering professional',
    'Data analyst',
    'Digital Transformation Strategy Leader',
    'Software Engineer Analyst',
    'Software QA',
    'System Administrator II',
    'Digital Strategist',
    'Cybersecurity Analyst',
    'Software QA Lead',
    'Devops engineer',
    'System Administrator',
    'System Engineer',
    'Infrastructure Delivery Manager',
    'Technical Training Developer',
    'Technology Professional',
    'Technical Operations Manager',
    'Data Science Graduate Student',
    'Network Security Administrator',
    'Technology Marketing Leader',
    'Network Manager',
    'Cybersecurity Leadership',
    'Technical Program Management Director',
    'Data Governance Senior Analyst',
    'Digital Learning Coach',
    'AI Research Engineer',
    'Digital Transformation Executive',
    'Software Engineering Team Lead',
    'DevOps Software Engineer',
    'Technical Operations',
    'Support Professional',
    'Technical Staff',
    'Software Application Engineer II',
    'Technical Content Specialist',
    'Technical Developer',
    'Technology Integration Manager',
    'Data Center Engineer lll',
    'Digital Transformation',
    'Software Engineering major',
    'Infrastructure Engineer',
    'Data Visualization Engineer',
    'Technology Transformation',
    'Data engineer',
    'Developer Analyst',
    'web developer',
    'Data science graduate student',
    'Database developer Architect',
    'Software and Data Engineer',
    'Technical Supervisor',
    'Technical Team Lead',
    'Security Consultant',
    'Programmer V',
    'Software Product Manager Intern',
    'Cloud Architect',
    'Technical Writer',
    'Software Development Management',
    'System Consultant',
    'Data Management Professional',
    'DATA CENTER TECHNICIAN',
    'Security guard',
    'Software Engineer in Test',
    'System Development',
    'System Administrator for L',
    'Technical Product Leader',
    'Cybersecurity Senior Analyst',
    'Developer Advocate',
    'Data Analyst II',
    'Digital Marketing Leader',
    'Programmer Analyst Sr',
    'Technical Support Engineer IV',
    'Technology Enthusiast',
    'CLOUD DEVOPS ENGINEER',
    'Network Security Engineer',
    'Digital Media Producer',
    'Software Implementation Specialist',
    'Cloud Platform Engineer',
    'Technology Product Management',
    'Software Quality Engineer',
    'Software Engineer III',
    'Data Manager',
    'Digital Marketing Director',
    'Software System Architect ',
    'Data Management Sr Consultant',
    'Software Systems Engineer',
    'Cloud Sales',
    'Data scientist',
    'Network Transformation Specialist',
    'Data Services Engineer',
    'Data Center Technician',
    'Software Architect',
    'Cybersecurity E',
    'Network Engineer Contractor',
    'DATABASE ADMINISTRATOR',
    'Cloud Database Administrator II',
    'Software Developer Consultant',
    'Network Operations Team Lead',
    'Technical Manager ',
    'Network and System administrator',
    'System Architect Engineer',
    'CyberSecurity Analyst',
    'Technical Service Engineer',
    'Cloud DevOps Engineer',
    'Database Administrator at',
    'Cybersecurity Enthusiast',
    'Software Services',
    'Data Analysis and Development',
    'DevOps Developer II',
    'Software engineer Intern',
    'DevOps Engineering Lead',
    'System Programmer',
    'System Analyst',
    'Technology Support Manager',
    'Technical Solutions Architect',
    'Network Systems Administrator Sr',
    'Software Development Team Lead',
    'System Security Engineer',
    'programmer analyst',
    'Software Test Engineer',
    'DevOps Engineering Intern',
    'Technical Fellow',
    'Technical Director',
    'Data Analytics Developer',
    'Software Developer Sr',
    'Cloud Operations Engineer',
    'Technical Architect',
    'Software Engineer II',
    'Cloud Security Architect',
    'Cloud security Engineer',
    'Technology Project Manager',
    'Cloud Operations Administrator',
    'Data Integration Analyst',
    'Digital Product Manager',
    'Digital Media Specialist',
    'System analyst III',
    'Network Support Admin',
    'Data Science',
    'Technical Designer',
    'Technical Leader and Architect',
    'Software engineering',
    'System Engineer Stf',
    'Security Software Engineer',
    'Technical Program Manager',
    'Software Engineer I',
    'Digital Designer',
    'AI Software Developer',
    'Software Engineer Lead',
    'Developer V',
    'Data Analytics',
    'Software Engineer Specialist',
    'Web Project Manager',
    'Network and System Administrator',
    'Technical Support Advisor',
    'Data Center Engineer',
    'Network and Systems Engineer',
    'System Engineer at',
    'Data Strategist',
    'Technical Integration Manager',
    'Software Engineering Professional',
    'DevOps Cloud Infrastructure Engineer',
    'Security and Cloud Engineer',
    'software engineer ',
    'Technical Service Representative',
    'Security Operations Manager',
    'Software Security Engineer',
    'Network and Security Analyst',
    'Data Analytics Manager',
    'Web Design ',
    'Technical Test Lead',
    'Digital Marketing Analytics Manager',
    'Data Science Specialist',
    'Web Architect',
    'Data Science Team Leader',
    'Digital Transformation Coach',
    'Software Developer II',
    'Technology Architect',
    'Data Science Student',
    'Software Quality Assurance Engineer',
    'Infrastructure Engineer ',
    'Data Center Operations Technician',
    'data processing programmer',
    'Security Specialist Solutions Architect',
    'Support Manager',
    'System architect',
    'Cloud Security Analyst',
    'Security Consulting Manager',
    'Web designer',
    'SYstem Engineer',
    'Data Engineering Manager',
    'Developer IV',
    'Engineer ',
    'Software Technology Leader',
    'Web Support Engineer',
    'Devops Engineer',
    'Data Scientist Intern',
    'Developer at',
    'Software Engineer AI',
    'Security Guard',
    'Software Operations Engineer II',
    'Software Engineering Consultant',
    'Technical Support Lead',
    'Technical Trainer',
    'DevOps Supervisor',
    'Cybersecurity Consultant',
    'Software Test Team Lead',
    'Database Administrator',
    'Software Engineer IV',
    'Software Engineering and AI',
    'Security Analyst',
    'Software and Data Engineering',
    'Technical Program Director',
    'Engineer III',
    'Software Quality Assurance Manager',
    'Data Engineering',
    'Data Engineering Lead',
    'Cloud Engineer',
    'Technical Sales Engineer',
    'SOFTWARE ENGINEER',
    'Data Science Leader',
    'Technical Product Director',
    'Cloud DevOps Leader',
    'Software Support',
    'Technology Developer',
    'Technical Operations Architect',
    'Infrastructure Solutions Architect',
    'System Integration',
    'Data Governance Lead',
    'Digital D Artist',
    'Software Engineer In Test',
    'Software Development Professional',
    'Cloud Systems Engineer',
    'Data Engineering Leader',
    'Programmer Analyst III',
    'web designer',
    'Software Programmer Analyst',
    'Data Solution Engineer III',
    'Technical Product Management',
    'System Validation Engineer',
    'Network and Security',
    'Software Engineer lll',
    'Technology Operations Coordinator',
    'Software Engineer E',
    'Software Quality Assurance Analyst',
    'Database Analyst',
    'Cloud Services Engineer',
    'Software Engineer Manager',
    'Infrastructure Architect Consultant',
    'Data driven',
    'System Engineer IV',
    'Technical Support IT',
    'Web developer',
    'Cybersecurity Administrator',
    'Software QA Automation Engineer',
    'Data Entry Specialist',
    'Software Administrator',
    'Technical Team Leader',
    'Programmer II',
    'Network Services Engineer',
    'Data Reporting Analyst',
    'Technology Project Management',
    'Security Solutions Engineer',
    'System engineer and coordinator',
    'Software builder',
    'Web Strategy',
    'Web Software Developer',
    'Digital Customer Experience',
    'Data Scientist ',
    'Software designer',
    'Technical and Business Writer',
    'Data Services',
    'Digital Transformation Specialist',
    'Software QA Analyst',
    'Software QA Engineer',
    'Technology Development Engineering Manager',
    'DevOps Manager',
    'Data analytics',
    'Technology Development Associate',
    'Technology Lead',
    'Technical Lead Engineer',
    'Software Engineering Leader',
    'Technical Product Marketing',
    'Software Support Specialist',
    'Technical Business Analyst',
    'AI Systems Engineer',
    'DevOps and Software Engineer',
    'Cloud Network Engineer',
    'Developer Representative',
    'Software Technician',
    'Data Reporting Advisory Analyst',
    'Technical Consultant',
    'Infrastructure Engineer II',
    'Data and Backend Engineer',
    'Cloud Technology Sales',
    'System Lead',
    'Software Engineering MTS',
    'Data Solutions Manager',
    'Digital Marketing Expert',
    'Technical Coordinator',
    'Data Management and Reporting',
    'Network Manager and Engineer',
    'Technical Delivery Manager',
    'Network Infrastructure Manager',
    'CyberSecurity Student',
    'Data Center Architect',
    'Software Development Manager',
    'Network Services Technician',
    'Software Application Engineer',
    'Digital Product',
    'Technology Representative',
    'Digital Design Engineer',
    'Software Programmer C',
    'System administrator',
    'Software design engineer',
    'Software Quality Assurance Tester',
    'software programmer',
    'Data Storyteller',
    'Cloud Enthusiast',
    'System Software Engineer',
    'Digital Content Manager',
    'Data Engineering Co',
    'Cloud Platform Administrator',
    'Cybersecurity student',
    'DevOps Lead',
    'Network Engineering',
    'Database Administrator ',
    'Security Architect',
    'System engineer',
    'Web Developer and Designer',
    'Database Support Analyst',
    'Data Engineering Consultant',
    'Technical Services Engineer',
    'Cloud Computing Engineer',
    'Data Team',
    'DevOps Technical Specialist',
    'Data Science student',
    'Cloud Support Engineer',
    'Software QA Manager',
    'Technical Design',
    'System Test Engineer',
    'Digital S',
    'System Engineer ',
    'Technical Solution Manager',
    'Data Engineer II',
    'security officer',
    'Security Assurance Consultant',
    'Software Developer III',
    'Data Platform',
    'Digital Engineering',
    'Technical Writer ',
    'Technical manager',
    'Technical Support Engineer II',
    'Software Test Engineer III',
    'System Engineering Manager',
    'Technical Student',
    'Programmer Analyst Supervisor',
    'Software Engineering Senior Manager',
    'Software Developer Team Leader',
    'Software programmer analyst',
    'DevOps Automation Cloud Engineer',
    'Technical Support Engineer ',
    'Software Developer Lead',
    'Data Integration Engineer',
    'Technical support specialist',
    'Devops and Software Engineer',
    'Support Technician',
    'System Support Engineer',
    'Technical Project Manager III',
    'Software Engineering Director',
    'Cloud Technical Architect',
    'Software Engineering Lead ',
    'Data Services Programmer',
    'Devops Engineering',
    'System Operations Manager',
    'Technology Investment Banking Associate',
    'Analyst Web Developer',
    'Data Driven Marketer',
    'Cloud Platform Software Engineer',
    'Cloud Systems Enthusiast',
    'Cybersecurity Engineer II',
    'Database and Systems Analyst',
    'Security Product Management',
    'Infrastructure Architect',
    'Security Team Leader',
    'Security Officer',
    'Web Development',
    'Network Admin',
    'Software E',
    'Network Infrastructure Engineer',
    'Software Development Intern',
    'Security Administrator',
    'DevOps Technical Lead',
    'SECURITY MANAGEMENT',
    'Software Development Engineer I',
    'Programmer at',
    'Data Systems Specialist',
    'DevOps Systems Engineer',
    'Digital Content Specialist',
    'Web Designer and Front',
    'DevOps Engineer',
    'Software Engineering Fellow',
    'Web Dev',
    'Data Systems Administrator',
    'Developer Specialist',
    'Network Support Team Leader',
    'Software QA Automation Engeneer',
    'System Security Administrator',
    'Technical Advisor',
    'Software Engineer Scientist',
    'Technical Program Manager IV',
    'Technical Support Specialist',
    'Software Automation Engineer',
    'AI Engineer',
    'Technology Strategy and Development',
    'Data Scientist II',
    'Cloud Native Engineer',
    'Software Tester',
    'Web programmer',
    'Programmer Analyst II',
    'Technical Lead of Service',
    'system programmer',
    'Developer I',
    'Software Developer ',
    'System Engineering Lead',
    'Security Software Engineer II',
    'Software Engineer Team Lead',
    'Analyst II',
    'Software Engineer Front',
    'Digital Transformation Developer',
    'Digital Product Executive',
    'Digital Service',
    'Network Specialist',
    'Data Engineering Intern',
    'Data Team Lead',
    'Technical Data Analyst',
    'Technology Leader',
    'Data Scientist Research',
    'Analyst web developer',
    'Data Systems Manager',
    'Engineer Technician',
    'Software Developer Analyst',
    'Engineer I',
    'Software Developer Specialist',
    'Cloud Security Control Assessor',
    'Data Entry Clerk',
    'Digital Storyteller',
    'Network Operations Analyst',
    'AI infrastructure engineer',
    'Data Science Lead',
    'Technology leadership',
    'Web Developer Analyst',
    'Data Engineer Intern',
    'Programmer Analyst Manager',
    'Security Solution Specialist',
    'Software Designer',
    'Software Engineer Sr',
    'Software Technical Fellow',
    'Technical Writer and Trainer',
    'Data and Analytics Manager',
    'Software tester',
    'Data Analytics Intern',
    'Digital Technology Leader',
    'Data System Engineer',
    'Data Systems Analyst',
    'Digital Analyst',
    'Technical Project Manager Sr',
    'Digital Operations L Manager',
    'Network Support Engineer',
    'SECURITY CONSULTANT',
    'Software Development Engineer ',
    'Technical Support Team Lead',
    'System Software Specialist',
    'Web Designer',
    'Data Coordinator',
    'Support Supervisor',
    'Technical Sales Representative',
    'Technical Support',
    'Data Quality Analysis',
    'Engineer IV',
    'CyberSecurity Professional',
    'Network Engineering Professional',
    'Digital Marketing Manager',
    'Software Engineering Manager',
    'System Admin',
    'Network and System Engineer',
    'Engineer Lead',
    'Network Technician',
    'Technical Solutions Engineer',
    'Security Engineer',
    'Digital Marketing Analytics Administrator',
    'Digital Service Expert',
    'Cloud Security Engineer',
    'Digital Systems Specialist',
    'Technology Support Associate',
    'Web Developer II',
    'Data Product Manager',
    'Digital Business Strategist',
    'Network Support Technician',
    'Support Engineer',
    'Digital and Marketing Executive',
    'Technical Business Associate',
    'Security Systems Analyst',
    'Cloud Infrastructure Engineer',
    'Technology leader with ',
    'Software Progammer',
    'Digital Marketing Coordinator',
    'Digital Technology Product',
]
